### PR TITLE
#158792524 Design Mockups

### PR DESCRIPTION
**Pull request by bibangamba**
#### What does this PR do?
Add UI mockups to the wireframes directory in the project root 

#### Description of tasks to be done?
* create artboards of the major UI screens using sketch
* add interactions using invision's craft
* add a gif of the interactions and the screens to a wireframes directory under the project root directory

#### How can this be manually tested?
view the mockups in the `wireframes` folder

#### What are the relevant pivotal tracker stories?
[#158792524](https://www.pivotaltracker.com/story/show/158792524)

#### Screenshots
image

image

image

### CODE REVIEW

**Comment by joshNic** [comment]
@bibangamba it looks like you have two detail screens please include only one detail screen

**Comment by joshNic** [comment]
@bibangamba I have also noticed you are intending to merge to master could you please merge to develop

**Comment by bibangamba** [comment]
Thanks for catching the merge to master problem. However, I didn't understand the feedback about `2 detail views`. I have 3 screens that are related to the details view; the details view its self, the pop up at the bottom for sharing, and the pop up for the profile picture

**Comment by joshNic** [comment]
This LGTM

**Pull request merged**
